### PR TITLE
Bugfix / Strict null comparison on isEmpty

### PR DESCRIPTION
**Pull request by HeberLZ**
Hi there,

I just updated the null check to make sure it's a strict comparison in order to prevent other falsy values from being accounted as empty and added an empty array check in case the value to be validated is an array, which is the case in the project I'm currently working on :)

Cheers!

### CODE REVIEW

**Comment by NewOldMax** [comment]
Hi,
thanks for your PR. Can you show an example where this case is relevant? It's not common to use arrays as input values. Maybe it's better to keep this in Custom rules

**Comment by HeberLZ** [comment]
I'm really sorry about this, created this pr a long time ago and somehow never saw your response with all the notifications, the use-case would be a SelectValidator with multiple=true, where the value would be an array. The same thing would happen when building a custom validator for the chip input which is not included in material-ui

**Comment by NewOldMax** [comment]
I think it's better to have different rule, like `isEmptyArray`. Otherwise we can have very complex `isEmpty` in future, like checking empty objects etc

**Comment by HeberLZ** [comment]
Makes sense, removed empty array check

**Comment by NewOldMax** [comment]
Thanks for your work

**Pull request merged**
