### PR TITLE
 return validation result on submit

### PR DESCRIPTION
**Pull request by ulisesbocchio**

### CODE REVIEW

**Comment by NewOldMax** [comment]
Hi,
Thanks for your work, but can you give some reasons for this changes? What kind of problem you trying to solve?

**Comment by ulisesbocchio** [comment]
I trigger the `submit` action directly through a reference to the `ValidatorForm`, so I gotta know weather validation was successful or not.

**Comment by NewOldMax** [comment]
If your validation was successful your `submit` function will execute, right? Also you have `onError` function that triggers when some validations are failed and `isFormValid` to get current form validation state

**Comment by ulisesbocchio** [comment]
yeah, I check wether the form is valid or not after submit. Since I'm triggering directly, it doesn't sound like a good idea to break apart the logic of checking into a 'onSubmit`. Also `isFormValid` re-runs validation in dry mode, which is a waste since the result is RIGHT THERE. Any other option has unnecessary overhead.

**Comment by NewOldMax** [comment]
Thanks for your work

**Pull request merged**
